In [1]:
import numpy as np

In [3]:
arr=np.array([1,7,13,105])

In [4]:
print(arr)

[  1   7  13 105]


In [7]:
arr1 = np.zeros(10)
arr2 = np.ones(10)
print(arr1)
print(arr2)
print(arr2*5)
print(arr2*10)
print(arr2*20)
print(arr2*25)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
[20. 20. 20. 20. 20. 20. 20. 20. 20. 20.]
[25. 25. 25. 25. 25. 25. 25. 25. 25. 25.]


In [10]:
arr3 = np.arange(30,71)
print(arr3)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [11]:
arr4 = np.arange(50,96)
print(arr4)

[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95]


In [12]:
arr5 = np.arange(20,80,2)
print(arr5)

[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66
 68 70 72 74 76 78]


In [14]:
arr6 = np.arange(21,80,2)
print(arr6)

[21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67
 69 71 73 75 77 79]


In [15]:
arr7= np.random.randint(10,40,15)
print(arr7)

[20 31 36 17 22 22 18 25 27 29 11 25 22 32 37]


In [16]:
arr8= np.random.randint(30,50,10)
print(arr8)

[32 32 37 38 39 30 41 45 30 49]


In [17]:
arr9= np.random.randint(50,90,20)
print(arr9)

[54 78 60 59 88 87 52 63 51 57 55 60 72 56 84 70 61 82 55 65]


In [19]:
arr10=np.array([1,5,6,3,2])
arr11=np.array([6,6,5,4,5])
print(arr10+arr11)
print(arr10*arr11)
print(arr10-arr11)
print(arr10/arr11)

[ 7 11 11  7  7]
[ 6 30 30 12 10]
[-5 -1  1 -1 -3]
[0.16666667 0.83333333 1.2        0.75       0.4       ]


In [27]:
arr12 = np.arange(10,22).reshape((3,4))
print(arr12)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [31]:
arr13 = np.identity(3)
print(arr13)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [34]:
arr14 = np.diag([1,2,3,4,5])
print(arr14)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [35]:
matrix = np.array([[4, 3, 2], [8, 7, 6]])
rows = matrix.shape[0]
columns = matrix.shape[1]
 
print("Rows:", rows)
print("Columns:", columns)


Rows: 2
Columns: 3
